### ISSUE TITLE
Coverage workflow fails

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_gui#24]
The Coverage workflow which also runs the codacy expects the CODACY_PROJECT_TOKEN secret to be defined. Probably this secret is not set up and, thus, the workflow fails. I do not know how we handle this for the other repos. However, I would like to have the same standards here.
Also I am confused that the tests directory is included in the coverage?!

**Comment by jan-janssen** [comment]
It seems to be fixed now and the token is available as far as I can see.

**Comment by jan-janssen** [comment]
In terms of measuring the coverage I noticed you are missing the `.coveragerc` file https://github.com/pyiron/pyiron_base/blob/master/.coveragerc I noticed it would be great to document all these things some where to have a small getting started guide for users who create a new pyiron module.
