### ISSUE TITLE
load_file breaks after import of `activate_gui`

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_gui#6]
Steps to reproduce
```
from pyiron_atomistics import Project
from pyiron_gui import activate_gui
pr = Project('test')
pr["image_file.tif"] 
>> UnicodeDecodeError as cause of OSError
```
While
```
from pyiron_atomistics import Project
pr = Project('test')
pr["image_file.tif"] 
>> Image output
from pyiron_gui import activate_gui
pr["image_file.tif"] 
```
works like a charm. Any ideas what could be causing this?

**Comment by niklassiemer** [comment]
@pmrv Could you maybe have a quick look what I miss here? Thanks!

**Comment by pmrv** [comment]
Will have a look next week, when I'm back.

**Comment by niklassiemer** [comment]
I assumed the PR #9 to fail since I `from pyiron_gui import activate_gui` in the test. However, this does not seem to break the test in this case!?

**Comment by niklassiemer** [comment]
Ok I cannot reproduce it at the master branch any more. Only from the PR #7... Nonetheless, I do not understand how this import can affect the `Project` creation which is exclusively using `pyiron_atomistics` functionality? (And, indeed, I did not touch `activate_gui`)

**Comment by niklassiemer** [comment]
To wrap up our findings in the meeting today:
The issue is caused by different `Image.registered_extensions()` depending on the order of the statements.
```
from pyiron_atomistics import Project
from pyiron_gui import ProjectBrowser
pr = Project('test')
pr["image_file.tif"] 
```
results in  `Image.registered_extensions() = {'.png': 'PNG', '.apng': 'PNG'}`, while 
```
from pyiron_atomistics import Project
pr = Project('test')
pr["image_file.tif"] 
from pyiron_gui import ProjectBrowser
```
results in a long `dict` including `.tif`.
